import React from "react";
import lottie from "lottie-web";

import UiUx from "../../assets/lotties/ui-ux-2.json";

export default function WhatWeDesign() {
  React.useEffect(() => {
    lottie.loadAnimation({
      container: document.querySelector("#ui-ux"),
      animationData: UiUx,
    });
  }, []);
  return (
    <>
      <section className="flex flex-col mx-auto xl:w-11/12 rounded-2xl">
        <div className="lg:p-20">
          <div className="flex flex-col lg:flex-row">
            <div className="flex items-center md:w-2/3 lg:w-full lg:-ml-20">
              <div id="ui-ux" />
            </div>
            <div className="flex flex-col lg:w-2/3 p-8 lg:p-0 items-center justify-center text-center">
              <>
                <button
                  data-popover-target="popover-default"
                  type="button"
                  class="text-taran-blue bg-unbxd-bg border-2 border-taran-orange focus:ring-4 focus:outline-none focus:ring-taran-orange font-medium rounded-lg text-3xl px-5 py-2.5 text-center"
                >
                  User Interface Design
                </button>
                <div
                  data-popover
                  id="popover-default"
                  role="tooltip"
                  class="inline-block absolute invisible z-10 w-72 text-sm font-light text-gray-500 bg-white rounded-lg border border-gray-200 shadow-sm opacity-0 transition-opacity duration-300 dark:bg-gray-800 dark:border-gray-600 dark:text-gray-400"
                >
                  <div class="p-3 space-y-2">
                    <h3 class="font-semibold text-gray-900 dark:text-white">
                      Activity growth - Incremental
                    </h3>
                    <p>
                      Report helps navigate cumulative growth of community
                      activities. Ideally, the chart should have a growing
                      trend, as stagnating chart signifies a significant
                      decrease of community activity.
                    </p>
                    <h3 class="font-semibold text-gray-900 dark:text-white">
                      Calculation
                    </h3>
                    <p>
                      For each date bucket, the all-time volume of activities is
                      calculated. This means that activities in period n contain
                      all activities up to period n, plus the activities
                      generated by your community in period.
                    </p>
                    <a
                      href="#"
                      class="flex items-center font-medium text-blue-600 dark:text-blue-500 dark:hover:text-blue-600 hover:text-blue-700"
                    >
                      Read more{" "}
                      <svg
                        class="ml-1 w-4 h-4"
                        aria-hidden="true"
                        fill="currentColor"
                        viewBox="0 0 20 20"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          fill-rule="evenodd"
                          d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                          clip-rule="evenodd"
                        ></path>
                      </svg>
                    </a>
                  </div>
                  <div data-popper-arrow></div>
                </div>
              </>
              <h1 className="text-xl lg:text-3xl text-taran-blue font-medium">
                So, what is UX/UI Design?
              </h1>
              <p className="text-base lg:text-xl pt-12">
                UX/UI Design is designing the user experience and user
                interface. Or, basically, designing your user’s journey
                throughout their entire use of your app or website.
              </p>
              <p className="text-base lg:text-xl pt-12">
                Common elements of UX/UI design include designing the
                navigation, information architecture, workflow, and heuristics
                of your product. This should all be done as you’re making sure
                all of these elements abide by consistent and relatable branding
                that encompasses a look and feel that’s tailored to your users.
              </p>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
